### ISSUE TITLE
pip3 exception

### ISSUE THREAD

**Issue by PhysixProject** [PhysixProject/physix#28]
pip install requests

Something odd is happening causing like 187 of /usr/lib/python3.7/shlex.py
to raise exception
raise ValueError("No closing quotation")

```
pip3 install requests
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 255, in run
    with self._build_session(options) as session:
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 93, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 344, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 108, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 674, in linux_distribution
    self.name() if full_distribution_name else self.id(),
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 712, in name
    name = self.os_release_attr('name') \
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 883, in os_release_attr
    return self._os_release_info.get(attribute, '')
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 550, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 922, in _os_release_info
    return self._parse_os_release_content(release_file)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 953, in _parse_os_release_content
    tokens = list(lexer)
  File "/usr/lib/python3.7/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib/python3.7/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.7/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
Traceback (most recent call last):
  File "/usr/bin/pip3", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/pip/_internal/__init__.py", line 78, in main
    return command.main(cmd_args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in main
    timeout=min(5, options.timeout)
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 93, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 344, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 108, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 674, in linux_distribution
    self.name() if full_distribution_name else self.id(),
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 712, in name
    name = self.os_release_attr('name') \
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 883, in os_release_attr
    return self._os_release_info.get(attribute, '')
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 550, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 922, in _os_release_info
    return self._parse_os_release_content(release_file)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/distro.py", line 953, in _parse_os_release_content
    tokens = list(lexer)
  File "/usr/lib/python3.7/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib/python3.7/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.7/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
- - - - - - - - - - - - - - - - - - - -
root@physix 1 [ physix ]# 

```

**Comment by PhysixProject** [comment]
This looks related.
https://github.com/pypa/pipenv/issues/2852

**Comment by PhysixProject** [comment]
also this:
https://github.com/containers/podman-compose/issues/129
